name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start MariaDB container
        run: |
          docker network create bookstack-network || true
          docker run -d \
          --name=bookstack_db \
          --network bookstack-network \
          -e PUID=1000 \
          -e PGID=1000 \
          -e TZ=Europe/London \
          -e MYSQL_ROOT_PASSWORD=yourdbpass \
          -e MYSQL_DATABASE=bookstackapp \
          -e MYSQL_USER=bookstack \
          -e MYSQL_PASSWORD=yourdbpass \
          --restart unless-stopped \
          lscr.io/linuxserver/mariadb:latest

      - name: Wait for database to be ready
        run: sleep 30

      - name: List files for debugging
        run: ls -la backupDB

      - name: Restore database from backup
        run: |
          docker cp ${{ github.workspace }}/backupDB/backup.sql bookstack_db:/backup.sql
          docker exec -i bookstack_db ls -la /backup.sql
          docker exec -i bookstack_db /bin/sh -c "/usr/bin/mysql -u bookstack -pyourdbpass bookstackapp < /backup.sql"

      - name: Start BookStack container
        run: |
          docker run -d \
            --name=bookstack \
            --network bookstack-network \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=Etc/UTC \
            -e APP_URL=http://localhost:6875 \
            -e DB_HOST=bookstack_db \
            -e DB_PORT=3306 \
            -e DB_USER=bookstack \
            -e DB_PASS=yourdbpass \
            -e DB_DATABASE=bookstackapp \
            -p 6875:80 \
            --restart unless-stopped \
            lscr.io/linuxserver/bookstack:latest

      - name: Wait for services to be ready
        run: sleep 30

      - name: Run tests
        run: ./gradlew test

      - name: Stop and remove containers
        run: |
          docker stop bookstack bookstack_db
          docker rm bookstack bookstack_db
          docker network rm bookstack-network